# Generated by Django 4.2.1 on 2023-06-09 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codeforces_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ranking'],
            },
        ),
        migrations.CreateModel(
            name='Cpe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('average', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='HBicycleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sna', models.CharField(max_length=100)),
                ('sbi', models.IntegerField(default=0)),
                ('tot', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-sbi',),
            },
        ),
        migrations.CreateModel(
            name='NKUSTnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('mprice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.phonemaker')),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
    ]
