# Generated by Django 4.2.1 on 2023-06-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_oil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codeforces_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(default=0)),
            ],
        ),
    ]
