# Generated by Django 4.2.1 on 2023-06-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_codeforces_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codeforces_data',
            options={'ordering': ['ranking']},
        ),
    ]
